# Key input info

In [1]:
root_name = '251026'
root_dir = rf"../../data/output/mosa/{root_name}"

In [2]:
import os
os.environ['GDAL_DATA'] = r'/usr/share/gdal'
from test4plot2 import plot_double, clearing, plot_cross_tab
from analysis import basic_stat, find_knee
from spatial_plot import plot_compared_cs, plot_zone_cs, match_cs, plot_delta_zone
from delay_analysis import plot_demand_heatmap
import pandas as pd
import geopandas as gpd
from pyproj import CRS
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from IPython.display import IFrame
warnings.simplefilter("ignore")

In [4]:
pd.options.display.float_format = '{:.1f}'.format  # 所有浮点数保留零位小数
means_stat_columns = ['bulit_num', 'fast_num_avg', 'slow_num_avg','large_num','medium_num','small_num','large_model','medium_model','small_model']
MEANS_PARETO = []
KNEES = []
SUPPLE = []
for name in os.listdir(root_dir):
    full_path = os.path.join(root_dir, name)
    if os.path.isdir(full_path) and name.endswith(f'_{root_name}'):
        city_name = name[:-len(f'_{root_name}')]
        print(city_name)
        cs_gdf = gpd.read_file(rf'../../data/input/cs_gdf/{city_name}.shp', crs=CRS.from_epsg(4507))  # 充电站
        cs_gdf = cs_gdf.drop_duplicates(subset=['node_id'], keep='first').reset_index(drop=True)
        cs_num = len(cs_gdf)
        OBJ_G = pd.read_csv(rf"../../data/output/mosa/{root_name}/{city_name}_{root_name}/inf_archive_objs.csv")
        VAR_G = pd.read_csv(rf"../../data/output/mosa/{root_name}/{city_name}_{root_name}/inf_archive_vars.csv")
        CV_G = pd.read_csv(rf"../../data/output/mosa/{root_name}/{city_name}_{root_name}/inf_archive_cvs.csv")
        OBJ_G = clearing(OBJ_G)
        print(f'{len(OBJ_G)}, {len(VAR_G)}')
        STAT_G = basic_stat(OBJ_G, VAR_G, CV_G, cs_num)
        MEANS_G = STAT_G[['bulit_num', 'fast_num_avg', 'slow_num_avg','large_num','medium_num','small_num']].mean()
        MODES_G = STAT_G.iloc[:, -3:].mode().iloc[0]
        OVER_G = pd.DataFrame([MEANS_G.tolist() + MODES_G.tolist()], 
                      columns=means_stat_columns)
        # 添加city_name和cs_num列并调整列顺序
        OVER_G['city_name'] = city_name
        OVER_G['candidate_num'] = cs_num
        OVER_G = OVER_G[['city_name', 'candidate_num'] + means_stat_columns]
        MEANS_PARETO.append(OVER_G)

        knee_no_G = find_knee(STAT_G)
        row_G = STAT_G.loc[STAT_G['solution_no'] == knee_no_G]
        row_G['city_name'] = city_name
        row_G['candidate_num'] = cs_num
        KNEES.append(row_G)

        vs_parking_df = pd.read_csv(rf"../../data/input/vs_parking_nodeid//{city_name}.csv")
        vehicle_count = vs_parking_df['v_name'].nunique()
        operational_distance = vs_parking_df['distance'].sum()
        SUPPLE.append([city_name,vehicle_count,operational_distance])
        
        
MEANS_PARETO = pd.concat(MEANS_PARETO, ignore_index=True).sort_values('candidate_num', ascending=False)
KNEES = pd.concat(KNEES, ignore_index=True).sort_values('candidate_num', ascending=False)
KNEES['built_ratio'] = KNEES['bulit_num'] / KNEES['candidate_num']
front = ['city_name']
rest = [c for c in KNEES.columns if c not in front]
# 重新排序
KNEES = KNEES[ front + rest ]
SUPPLE = pd.DataFrame(SUPPLE, columns=['city_name','vehicle_count','operational_distance'])

七台河市
118, 118
三亚市
210, 211
三明市
191, 194
三门峡市
138, 138
上海市
356, 384
上饶市
185, 185
东莞市
254, 293
东营市
235, 238
中山市
263, 297
临汾市
138, 138
丹东市
162, 162
乌兰察布市
49, 49
乌鲁木齐市
247, 278
九江市
170, 171
云浮市
108, 108
佛山市
302, 346
佳木斯市
150, 150
保定市
219, 219
信阳市
225, 225
六安市
200, 217
六盘水市
197, 197
兰州市
253, 270
内江市
183, 183
包头市
199, 200
北京市
277, 282
北海市
140, 140
十堰市
207, 215
南京市
317, 346
南充市
230, 231
南宁市
229, 237
南平市
201, 203
南昌市
249, 286
南通市
236, 268
南阳市
341, 341
厦门市
253, 292
双鸭山市
110, 110
台州市
190, 192
吉安市
153, 153
吉林市
216, 224
吕梁市
119, 119
周口市
163, 163
呼和浩特市
306, 306
咸宁市
88, 88
咸阳市
276, 276
哈密市
152, 152
哈尔滨市
300, 371
商丘市
271, 271
嘉兴市
225, 231
四平市
106, 106
固原市
14, 14
大同市
243, 243
大庆市
204, 204
天水市
270, 270
天津市
290, 332
太原市
228, 236
威海市
183, 204
娄底市
100, 100
宁德市
174, 174
宁波市
303, 330
安庆市
190, 190
安阳市
78, 78
安顺市
132, 132
宜宾市
248, 248
宜昌市
216, 216
宜春市
156, 156
宝鸡市
239, 239
宿州市
170, 170
宿迁市
223, 223
岳阳市
247, 247
常州市
261, 273
常德市
241, 241
平顶山市
193, 193
广州市
271, 271
庆阳市
47, 47
廊坊市
255, 255
开封市
215, 215
张家口市
227, 227
张掖市
109, 109
徐州市
174, 178
德州市
181, 181
忻州市
48, 48
怀化市
146, 146
惠州市
281, 282
成都市
330, 369
扬州市
247, 258
承德市
217, 217
抚州市
159, 159
抚顺市
166, 166
拉萨市
194, 194
揭阳市
83, 83
攀枝花市
64, 64
新乡市
177, 177
新余市
101, 101
日照市
276, 277
昆明市
247, 302
昭通市
237, 237
晋城市
79, 79
景德镇市
124, 124
曲靖市
191, 191
朔州市
111, 111
朝阳市
77, 77
来宾市
68, 68
杭州市
323, 376
松原市
55, 55
枣庄市
166, 166
柳州市
196, 196
桂林市
187, 188
梅州市
205, 209
梧州市
140, 140
武汉市
245, 255
毕节市
143, 143
永州市
87, 87
汕头市
272, 274
汕尾市
106, 106
江门市
155, 161
沈阳市
290, 328
沧州市
94, 94
河池市
209, 209
河源市
57, 57
泉州市
222, 222
泰安市
231, 238
泰州市
276, 276
泸州市
181, 191
洛阳市
294, 294
济南市
298, 337
济宁市
252, 264
海口市
217, 223
淄博市
243, 258
淮北市
165, 165
淮南市
192, 192
淮安市
178, 178
深圳市
298, 298
清远市
159, 162
温州市
281, 286
湖州市
205, 221
湘潭市
139, 139
湛江市
183, 183
滁州市
158, 158
滨州市
227, 228
漯河市
60, 60
漳州市
173, 191
潍坊市
257, 257
潮州市
156, 156
濮阳市
177, 177
烟台市
254, 254
焦作市
168, 168
牡丹江市
220, 220
玉林市
123, 123
玉溪市
169, 169
珠海市
228, 234
百色市
164, 164
益阳市
194, 194
盐城市
247, 248
盘锦市
224, 224
眉山市
231, 231
石家庄市
271, 284
福州市
265, 265
秦皇岛市
197, 197
绍兴市
247, 267
绥化市
37, 37
绵阳市
221, 239
聊城市
192, 205
肇庆市
201, 201
自贡市
173, 176
舟山市
221, 221
芜湖市
256, 263
苏州市
304, 316
茂名市
205, 205
荆州市
198, 198
荆门市
188, 189
莆田市
200, 200
菏泽市
236, 236
萍乡市
68, 68
营口市
198, 198
蚌埠市
156, 156
衡水市
169, 169
衡阳市
250, 250
衢州市
161, 165
襄阳市
222, 222
西宁市
242, 242
西安市
198, 202
贵港市
116, 116
贵阳市
257, 288
资阳市
107, 107
赣州市
201, 206
赤峰市
87, 87
辽阳市
120, 120
达州市
218, 218
运城市
262, 262
连云港市
249, 261
通化市
119, 119
遵义市
220, 220
邢台市
209, 214
邯郸市
227, 227
邵阳市
208, 208
郴州市
216, 217
鄂尔多斯市
247, 247
酒泉市
52, 52
重庆市
263, 266
金华市
225, 265
铁岭市
13, 13
铜仁市
104, 104
铜川市
100, 100
铜陵市
201, 203
银川市
229, 229
锦州市
112, 112
镇江市
191, 195
长春市
312, 312
长沙市
250, 269
长治市
204, 211
阜阳市
197, 197
阳江市
54, 54
随州市
58, 58
雅安市
50, 50
青岛市
243, 244
鞍山市
171, 180
马鞍山市
241, 241
驻马店市
204, 204
鹤壁市
112, 112
鹰潭市
31, 31
黄石市
204, 204
黑河市
47, 47
齐齐哈尔市
221, 221
龙岩市
212, 212

## 1. Overvall

### 1.1 Average statistics of Pareto solutions

In [7]:
MEANS_PARETO = MEANS_PARETO.reset_index(drop=True)
MEANS_PARETO

,city_name,candidate_num,bulit_num,fast_num_avg,slow_num_avg,large_num,medium_num,small_num,large_model,medium_model,small_model
0,北京市,1551,803.9,1.6,9.1,371.3,18.6,9.7,4.0,2.0,1.0
1,重庆市,1260,616.2,1.6,8.5,63.4,22.3,0.4,4.0,2.0,1.0
2,上海市,1241,546.0,1.7,10.0,178.8,31.3,0.1,4.0,2.0,1.0
3,杭州市,1098,468.0,0.8,7.0,360.2,79.4,4.0,4.0,2.0,1.0
4,广州市,944,440.6,1.6,9.4,179.1,14.8,3.0,4.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
219,忻州市,14,5.4,4.1,10.7,4.0,0.0,0.0,4.0,2.0,0.0
220,庆阳市,14,6.0,10.1,17.1,0.2,0.0,0.0,4.0,2.0,0.0
221,乌兰察布市,12,5.5,4.1,13.9,0.0,8.3,0.0,4.0,2.0,1.0
222,固原市,11,4.2,0.3,3.9,0.3,0.0,0.0,4.0,2.0,1.0
223,铁岭市,8,3.6,6.5,13.2,0.0,0.0,0.0,4.0,2.0,2.0

### 1.2 Average statistics of knee points

In [10]:
KNEES['built_ratio'] = KNEES['built_ratio'].map('{:.2f}'.format)
KNEES = KNEES.reset_index(drop=True)
KNEES
KNEES.to_csv(r'E:/Manufacture/Python/cnbus/data/224cities_output.csv')

### 1.3 Key indicators from knee points

In [15]:
SUPPLE = pd.merge(SUPPLE,KNEES,on='city_name')
SUPPLE['vehicle_count'] = SUPPLE['vehicle_count']+SUPPLE['large_num']+SUPPLE['medium_num']+SUPPLE['small_num']
SUPPLE['cost_per_km'] = SUPPLE['obj1']/SUPPLE['operational_distance']
SUPPLE['emission_per_km'] = SUPPLE['obj2']/SUPPLE['operational_distance']
SUPPLE['station_per_km'] = SUPPLE['bulit_num']/SUPPLE['operational_distance']
SUPPLE['charger_per_km'] = (SUPPLE['fast_num_avg']+SUPPLE['slow_num_avg'])*SUPPLE['bulit_num']/SUPPLE['operational_distance']
SUPPLE['ev_per_km'] = SUPPLE['vehicle_count'] / SUPPLE['operational_distance']
SUPPLE = SUPPLE[['city_name','cost_per_km','emission_per_km','station_per_km','charger_per_km','ev_per_km']]

KeyError: 'vehicle_count'

In [21]:
pd.options.display.float_format = '{:.10f}'.format
SUPPLE

,city_name,cost_per_km,emission_per_km,station_per_km,charger_per_km,ev_per_km,solution_no,obj1,obj2,bulit_num,fast_num_avg,slow_num_avg,large_num,medium_num,small_num,large_model,medium_model,small_model,candidate_num,built_ratio
0,上海市,0.0000020041,0.0000643924,0.0000004296,0.0000020673,0.0000165867,SA145287,2131.7026414970,68493.3436384737,457,0.1225382932,4.6892778993,4,1,0,4,2,1,1241,0.37
1,乌鲁木齐市,0.0000023505,0.0000674770,0.0000002128,0.0000022010,0.0000203992,SA146838,386.5803382430,11097.7617286352,35,0.4857142857,9.8571428571,0,0,0,4,2,1,194,0.18
2,北京市,0.0000022674,0.0000670682,0.0000004410,0.0000022451,0.0000184820,SA146903,3413.5460655350,100972.3606564851,664,0.2078313253,4.8825301205,9,0,2,4,2,1,1551,0.43
3,南京市,0.0000023488,0.0000657308,0.0000004332,0.0000026011,0.0000185719,SA146660,1198.3156951548,33534.4459442144,221,0.3484162896,5.6561085973,2,0,0,4,2,1,643,0.34
4,哈尔滨市,0.0000024312,0.0000662549,0.0000003774,0.0000029034,0.0000195917,SA145401,650.6280509382,17730.7280259584,101,0.3663366337,7.3267326733,2,0,0,4,2,1,341,0.30
5,威海市,0.0000017391,0.0000660853,0.0000003872,0.0000023435,0.0000129710,SA145021,170.6835516949,6485.7409553219,38,0.2894736842,5.7631578947,0,0,0,4,2,1,189,0.20
6,广州市,0.0000022705,0.0000648259,0.0000004109,0.0000021428,0.0000176408,SA146159,2110.6234680394,60262.5123715960,382,0.1413612565,5.0732984293,4,0,1,4,2,1,944,0.40
7,成都市,0.0000021450,0.0000641468,0.0000004703,0.0000024593,0.0000181449,SA145325,1432.1951865144,42829.6162568184,314,0.1369426752,5.0923566879,0,0,0,4,2,1,901,0.35
8,昆明市,0.0000028181,0.0000651505,0.0000004372,0.0000025900,0.0000272285,SA146758,341.6490951469,7898.4123642809,53,0.0000000000,5.9245283019,0,0,0,4,2,1,253,0.21
9,武汉市,0.0000020763,0.0000653248,0.0000004948,0.0000019951,0.0000156819,SA144304,1057.3693410923,33266.6809866699,252,0.0912698413,3.9404761905,2,0,0,4,2,1,701,0.36
10,沈阳市,0.0000022857,0.0000654235,0.0000003700,0.0000024053,0.0000183261,SA146783,518.8581658468,14851.0156447888,84,0.0833333333,6.4166666667,0,0,0,4,2,1,324,0.26
11,深圳市,0.0000018908,0.0000649276,0.0000002613,0.0000022325,0.0000154315,SA145865,1396.6109599079,47956.8062646021,193,0.3575129534,8.1865284974,0,0,0,4,2,1,626,0.31
12,湘潭市,0.0000021321,0.0000682500,0.0000002493,0.0000019389,0.0000170065,SA145443,76.9755025678,2464.0804025993,9,0.0000000000,7.7777777778,0,0,0,4,2,1,53,0.17
13,珠海市,0.0000015936,0.0000667756,0.0000001316,0.0000016475,0.0000126644,SA146732,302.7589756867,12686.0959433088,25,2.0800000000,10.4400000000,0,0,0,4,2,1,149,0.17
14,绵阳市,0.0000020920,0.0000667631,0.0000001840,0.0000017809,0.0000190751,SA146980,284.2669759563,9072.0486118799,25,1.4800000000,8.2000000000,0,0,0,4,2,1,147,0.17
15,莆田市,0.0000014840,0.0000674412,0.0000002358,0.0000017125,0.0000109328,SA144981,119.5849775023,5434.6225628183,19,0.4736842105,6.7894736842,0,0,0,4,2,0,88,0.22
16,西安市,0.0000018677,0.0000652922,0.0000003021,0.0000021247,0.0000151457,SA143677,772.6963557334,27012.2985153478,125,0.1440000000,6.8880000000,0,0,0,4,2,1,451,0.28
17,重庆市,0.0000025898,0.0000655138,0.0000006284,0.0000024755,0.0000222484,SA139616,2176.0585065140,55047.4043742720,528,0.1685606061,3.7708333333,2,0,0,4,2,1,1260,0.42

## 2. Pareto front

In [13]:
city_name = '北京市'
OBJ_G = pd.read_csv(rf"../../data/output/{root_name}/{city_name}_{root_name}/archive_objs.csv")
OBJ_G = clearing(OBJ_G)
plot_double(OBJ_G,save_pic=False)

FileNotFoundError: [Errno 2] No such file or directory: '../../data/output/250630/北京市_250630/archive_objs.csv'